stages:
  - build

Build:
  stage: build
  before_script:
    - apt update && apt -y install make autoconf gcc g++ nvidia-cuda-toolkit libsdl2-dev

  script:
    - echo "Starting compilation the code..."
    - make -Bj
    - echo "Compilation complete."

  artifacts:
    paths:
      - mandelbrot
